CREATE DATABASE IF NOT EXISTS `store`;
CREATE DATABASE IF NOT EXISTS `delivery`;
CREATE DATABASE IF NOT EXISTS `order`;
CREATE DATABASE IF NOT EXISTS `account`;
CREATE DATABASE IF NOT EXISTS `courier`;
